name: soglio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - tensorflow=2.16
  - tensorflow-probability=0.24.0
  - tensorboard=2.16
  - numpy=1.26
  - matplotlib=3.8
  - seaborn
  - pandas
  - jupyterlab=4.0
  - ipywidgets  # <-- This is the only required addition
  - pip
  - scikit-learn
  - tqdm
  - pip:
    - tf2onnx==1.16.0
    - onnx==1.15.0
    - pydot==2.0.0
    - graphviz==0.20.1
    - git+https://github.com/Gilles86/braincoder.git@transformation_refactor
